version: "3.9"  # optional since v1.27.0
services: 
    web:
        build: lamp/.
        volumes:
            - "htdocs:/var/www/html"
            - "userdata:/root"
        ports:
            - "80:80"
        container_name: "lamp"
        image: "git.selfmade.ninja:5050/lahtp-common/dockers-for-lahtp-advanced"
        hostname: "lahtp-advanced"
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        container_name: "lamp_db"
        ports:
            - "3306:3306"

volumes: 
    htdocs:
    userdata: